spring:
  profiles: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: cropy
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    
---

spring:
  profiles: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: cropy
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    
---    

spring:
  profiles: test
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: cropy
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    
---   

spring:
  profiles: uat
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: cropy
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    
---

spring:
  profiles:
    active: uat
